// registry/react/ui/toaster.tsx
"use client";

import * as React from "react";
import { createPortal } from "react-dom";

import { cn } from "@/lib/utils";
import { Toast } from "./toast";
import {
  toastStore,
  type ToastData,
  type ToastPosition,
  type ToastSize,
  type ToastVariant,
} from "./toast-store";

// Stable reference for SSR: getServerSnapshot must return the same value every
// call, otherwise useSyncExternalStore re-renders forever.
const EMPTY: ToastData[] = [];

const POSITION_CLASSES: Record<ToastPosition, string> = {
  "top-left": "top-0 left-0 sm:items-start",
  "top-center": "top-0 left-1/2 -translate-x-1/2 sm:items-center",
  "top-right": "top-0 right-0 sm:items-end",
  "bottom-left": "bottom-0 left-0 flex-col-reverse sm:items-start",
  "bottom-center":
    "bottom-0 left-1/2 -translate-x-1/2 flex-col-reverse sm:items-center",
  "bottom-right": "bottom-0 right-0 flex-col-reverse sm:items-end",
};

// Sonner-style stack tuning.
const PEEK = 14; // px each card behind peeks out when collapsed
const GAP = 14; // px between cards when expanded
const SCALE_STEP = 0.05; // scale reduction per card behind
const MAX_VISIBLE = 3; // cards shown before the rest fade out when collapsed

export interface ToasterProps {
  /** Default position for toasts that don't set their own. */
  position?: ToastPosition;
  /** Default visual treatment for toasts that don't set their own. */
  variant?: ToastVariant;
  /** Default size for toasts that don't set their own. */
  size?: ToastSize;
  /** @deprecated Use `variant="outline"`. */
  richColors?: boolean;
  /** Show toasts as a flat list instead of a collapsible stack. */
  expand?: boolean;
}

export function Toaster({
  position = "bottom-right",
  variant = "default",
  size = "default",
  richColors = false,
  expand = false,
}: ToasterProps) {
  const toasts = React.useSyncExternalStore(
    toastStore.subscribe,
    toastStore.getSnapshot,
    () => EMPTY,
  );
  const [mounted, setMounted] = React.useState(false);
  React.useEffect(() => setMounted(true), []);

  const [heights, setHeights] = React.useState<Record<string | number, number>>(
    {},
  );
  const [expandedMap, setExpandedMap] = React.useState<Record<string, boolean>>(
    {},
  );

  const reportHeight = React.useCallback((id: string | number, h: number) => {
    setHeights((prev) => (prev[id] === h ? prev : { ...prev, [id]: h }));
  }, []);

  const setGroupExpanded = React.useCallback((pos: string, val: boolean) => {
    setExpandedMap((prev) =>
      prev[pos] === val ? prev : { ...prev, [pos]: val },
    );
  }, []);

  if (!mounted) return null;

  // Toaster-level default; `richColors` is a deprecated alias for "outline".
  const defaultVariant: ToastVariant =
    variant !== "default" ? variant : richColors ? "outline" : "default";

  // Group toasts by their effective position.
  const groups = new Map<ToastPosition, ToastData[]>();
  for (const t of toasts) {
    const pos = t.position ?? position;
    if (!groups.has(pos)) groups.set(pos, []);
    groups.get(pos)!.push({
      ...t,
      position: pos,
      variant: t.variant ?? (t.richColors ? "outline" : defaultVariant),
      size: t.size ?? size,
    });
  }

  const stacked = !expand;

  return createPortal(
    <>
      {[...groups.entries()].map(([pos, items]) => {
        if (!stacked) {
          return (
            <ol
              key={pos}
              className={cn(
                "pointer-events-none fixed z-[100] flex max-h-screen w-full flex-col gap-2 p-4 sm:max-w-[380px]",
                POSITION_CLASSES[pos],
              )}
            >
              {items.map((t) => (
                <Toast key={t.id} toast={t} />
              ))}
            </ol>
          );
        }

        // --- Stacked layout ---
        const anchorBottom = !pos.startsWith("top");
        const dir = pos.startsWith("top") ? 1 : -1;
        const groupExpanded = !!expandedMap[pos];
        const h = (id: string | number) => heights[id] ?? 76;

        const frontHeight = items[0] ? h(items[0].id) : 0;
        const visibleBehind = Math.min(items.length - 1, MAX_VISIBLE - 1);
        const total = items.reduce((s, t) => s + h(t.id), 0);
        const containerHeight = groupExpanded
          ? total + Math.max(0, items.length - 1) * GAP
          : frontHeight + visibleBehind * PEEK;

        return (
          <ol
            key={pos}
            className={cn(
              "pointer-events-none fixed z-[100] flex w-full p-4 sm:max-w-[380px]",
              POSITION_CLASSES[pos],
            )}
          >
            <div
              onMouseEnter={() => setGroupExpanded(pos, true)}
              onMouseLeave={() => setGroupExpanded(pos, false)}
              className="pointer-events-auto relative w-full transition-[height] duration-300 ease-out"
              style={{ height: containerHeight }}
            >
              {items.map((t, i) => {
                let expandedOffset = 0;
                for (let k = 0; k < i; k++)
                  expandedOffset += h(items[k].id) + GAP;
                const stackY = groupExpanded
                  ? dir * expandedOffset
                  : dir * i * PEEK;
                const stackScale = groupExpanded ? 1 : 1 - i * SCALE_STEP;
                const stackOpacity = groupExpanded
                  ? 1
                  : i < MAX_VISIBLE
                    ? 1
                    : 0;
                return (
                  <Toast
                    key={t.id}
                    toast={t}
                    stacked
                    expanded={groupExpanded}
                    anchorBottom={anchorBottom}
                    stackY={stackY}
                    stackScale={stackScale}
                    stackOpacity={stackOpacity}
                    stackZ={items.length - i}
                    onHeight={reportHeight}
                  />
                );
              })}
            </div>
          </ol>
        );
      })}
    </>,
    document.body,
  );
}

export { toast } from "./toast-store";

// registry/vue/ui/Toaster.vue
<script setup lang="ts">
import { computed, reactive } from "vue";

import { cn } from "@/lib/utils";
import Toast from "./Toast.vue";
import {
  toasts,
  type ToastData,
  type ToastPosition,
  type ToastSize,
  type ToastVariant,
} from "./useToast";

const props = withDefaults(
  defineProps<{
    position?: ToastPosition;
    /** Default visual treatment for toasts that don't set their own. */
    variant?: ToastVariant;
    /** Default size for toasts that don't set their own. */
    size?: ToastSize;
    /** @deprecated Use `variant="outline"`. */
    richColors?: boolean;
    expand?: boolean;
  }>(),
  {
    position: "bottom-right",
    variant: "default",
    size: "default",
    richColors: false,
    expand: false,
  },
);

const POSITION_CLASSES: Record<ToastPosition, string> = {
  "top-left": "top-0 left-0 sm:items-start",
  "top-center": "top-0 left-1/2 -translate-x-1/2 sm:items-center",
  "top-right": "top-0 right-0 sm:items-end",
  "bottom-left": "bottom-0 left-0 flex-col-reverse sm:items-start",
  "bottom-center":
    "bottom-0 left-1/2 -translate-x-1/2 flex-col-reverse sm:items-center",
  "bottom-right": "bottom-0 right-0 flex-col-reverse sm:items-end",
};

// Sonner-style stack tuning.
const PEEK = 14;
const GAP = 14;
const SCALE_STEP = 0.05;
const MAX_VISIBLE = 3;

const heights = reactive<Record<string | number, number>>({});
const expandedMap = reactive<Record<string, boolean>>({});

function registerHeight(id: string | number, h: number) {
  if (heights[id] !== h) heights[id] = h;
}
const h = (id: string | number) => heights[id] ?? 76;

const groups = computed(() => {
  // Toaster-level default; `richColors` is a deprecated alias for "outline".
  const defaultVariant: ToastVariant =
    props.variant !== "default"
      ? props.variant
      : props.richColors
        ? "outline"
        : "default";
  const map = new Map<ToastPosition, ToastData[]>();
  for (const t of toasts) {
    const pos = t.position ?? props.position;
    if (!map.has(pos)) map.set(pos, []);
    map.get(pos)!.push({
      ...t,
      position: pos,
      variant: t.variant ?? (t.richColors ? "outline" : defaultVariant),
      size: t.size ?? props.size,
    });
  }
  return [...map.entries()];
});

function containerHeight(items: ToastData[], pos: string): number {
  const expanded = !!expandedMap[pos];
  if (expanded) {
    const total = items.reduce((s, t) => s + h(t.id), 0);
    return total + Math.max(0, items.length - 1) * GAP;
  }
  const front = items[0] ? h(items[0].id) : 0;
  const visibleBehind = Math.min(items.length - 1, MAX_VISIBLE - 1);
  return front + visibleBehind * PEEK;
}

function layoutFor(items: ToastData[], i: number, pos: ToastPosition) {
  const expanded = !!expandedMap[pos];
  const dir = pos.startsWith("top") ? 1 : -1;
  let expandedOffset = 0;
  for (let k = 0; k < i; k++) expandedOffset += h(items[k].id) + GAP;
  return {
    anchorBottom: !pos.startsWith("top"),
    stackY: expanded ? dir * expandedOffset : dir * i * PEEK,
    stackScale: expanded ? 1 : 1 - i * SCALE_STEP,
    stackOpacity: expanded ? 1 : i < MAX_VISIBLE ? 1 : 0,
    stackZ: items.length - i,
  };
}
</script>

<template>
  <Teleport to="body">
    <!-- Flat-list mode -->
    <template v-if="expand">
      <!-- Enter/exit are self-managed inside <Toast> (mirrors React); the
           TransitionGroup only FLIP-animates siblings reflowing on removal. -->
      <TransitionGroup
        v-for="[pos, items] in groups"
        :key="pos"
        tag="ol"
        :class="
          cn(
            'pointer-events-none fixed z-[100] flex max-h-screen w-full flex-col gap-2 p-4 sm:max-w-[380px]',
            POSITION_CLASSES[pos],
          )
        "
        move-class="transition-transform duration-300 motion-reduce:transition-none"
      >
        <Toast v-for="t in items" :key="t.id" :toast="t" />
      </TransitionGroup>
    </template>

    <!-- Stacked mode (default) -->
    <template v-else>
      <ol
        v-for="[pos, items] in groups"
        :key="pos"
        :class="
          cn(
            'pointer-events-none fixed z-[100] flex w-full p-4 sm:max-w-[380px]',
            POSITION_CLASSES[pos],
          )
        "
      >
        <div
          class="pointer-events-auto relative w-full transition-[height] duration-300 ease-out"
          :style="{ height: containerHeight(items, pos) + 'px' }"
          @mouseenter="expandedMap[pos] = true"
          @mouseleave="expandedMap[pos] = false"
        >
          <Toast
            v-for="(t, i) in items"
            :key="t.id"
            :toast="t"
            stacked
            :expanded="!!expandedMap[pos]"
            :anchor-bottom="layoutFor(items, i, pos).anchorBottom"
            :stack-y="layoutFor(items, i, pos).stackY"
            :stack-scale="layoutFor(items, i, pos).stackScale"
            :stack-opacity="layoutFor(items, i, pos).stackOpacity"
            :stack-z="layoutFor(items, i, pos).stackZ"
            :report-height="registerHeight"
          />
        </div>
      </ol>
    </template>
  </Teleport>
</template>
